# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import raft_pb2 as raft__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in raft_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RaftStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.request_vote = channel.unary_unary(
                '/raft.Raft/request_vote',
                request_serializer=raft__pb2.VoteRequest.SerializeToString,
                response_deserializer=raft__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.append_entry = channel.unary_unary(
                '/raft.Raft/append_entry',
                request_serializer=raft__pb2.AppendEntryRequest.SerializeToString,
                response_deserializer=raft__pb2.AppendEntryResponse.FromString,
                _registered_method=True)
        self.commit_entries = channel.unary_unary(
                '/raft.Raft/commit_entries',
                request_serializer=raft__pb2.CommitRequest.SerializeToString,
                response_deserializer=raft__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.client_request = channel.unary_unary(
                '/raft.Raft/client_request',
                request_serializer=raft__pb2.ClientRequest.SerializeToString,
                response_deserializer=raft__pb2.ClientResponse.FromString,
                _registered_method=True)


class RaftServicer:
    """Missing associated documentation comment in .proto file."""

    def request_vote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def append_entry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def commit_entries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def client_request(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'request_vote': grpc.unary_unary_rpc_method_handler(
                    servicer.request_vote,
                    request_deserializer=raft__pb2.VoteRequest.FromString,
                    response_serializer=raft__pb2.VoteResponse.SerializeToString,
            ),
            'append_entry': grpc.unary_unary_rpc_method_handler(
                    servicer.append_entry,
                    request_deserializer=raft__pb2.AppendEntryRequest.FromString,
                    response_serializer=raft__pb2.AppendEntryResponse.SerializeToString,
            ),
            'commit_entries': grpc.unary_unary_rpc_method_handler(
                    servicer.commit_entries,
                    request_deserializer=raft__pb2.CommitRequest.FromString,
                    response_serializer=raft__pb2.CommitResponse.SerializeToString,
            ),
            'client_request': grpc.unary_unary_rpc_method_handler(
                    servicer.client_request,
                    request_deserializer=raft__pb2.ClientRequest.FromString,
                    response_serializer=raft__pb2.ClientResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'raft.Raft', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('raft.Raft', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Raft:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def request_vote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raft.Raft/request_vote',
            raft__pb2.VoteRequest.SerializeToString,
            raft__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def append_entry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raft.Raft/append_entry',
            raft__pb2.AppendEntryRequest.SerializeToString,
            raft__pb2.AppendEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def commit_entries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raft.Raft/commit_entries',
            raft__pb2.CommitRequest.SerializeToString,
            raft__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def client_request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raft.Raft/client_request',
            raft__pb2.ClientRequest.SerializeToString,
            raft__pb2.ClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClientStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.client_put = channel.unary_unary(
                '/raft.Client/client_put',
                request_serializer=raft__pb2.ClientPutRequest.SerializeToString,
                response_deserializer=raft__pb2.ClientPutResponse.FromString,
                _registered_method=True)
        self.client_get = channel.unary_unary(
                '/raft.Client/client_get',
                request_serializer=raft__pb2.ClientGetRequest.SerializeToString,
                response_deserializer=raft__pb2.ClientGetResponse.FromString,
                _registered_method=True)


class ClientServicer:
    """Missing associated documentation comment in .proto file."""

    def client_put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def client_get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'client_put': grpc.unary_unary_rpc_method_handler(
                    servicer.client_put,
                    request_deserializer=raft__pb2.ClientPutRequest.FromString,
                    response_serializer=raft__pb2.ClientPutResponse.SerializeToString,
            ),
            'client_get': grpc.unary_unary_rpc_method_handler(
                    servicer.client_get,
                    request_deserializer=raft__pb2.ClientGetRequest.FromString,
                    response_serializer=raft__pb2.ClientGetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'raft.Client', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('raft.Client', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Client:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def client_put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raft.Client/client_put',
            raft__pb2.ClientPutRequest.SerializeToString,
            raft__pb2.ClientPutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def client_get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/raft.Client/client_get',
            raft__pb2.ClientGetRequest.SerializeToString,
            raft__pb2.ClientGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
